name: Scripts & Make Build
on: [push, pull_request]
env:
  CACHE_NUMBER: 2
  COMPILER_VERSION: 2022.0.3

jobs:
  build-linux-gnu:
    name: gnu_linux_${{ matrix.program }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        program:
          - background
          - convert
          - env2mod
          - flush
          - makepo
          - mergepo
          - smokediff
          - smokeview
          - smokezip
          - timep
          - wind2fds
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install build-essential freeglut3-dev libx11-dev libxmu-dev libxi-dev
          pushd Build/${{ matrix.program }}/gnu_linux_64 || pushd Build/${{ matrix.program }}/gcc_linux_64
          ./make_${{ matrix.program }}.sh
          popd
